### ISSUE TITLE
Taxa/samples not featuring in Classify

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#18]
I've so far only noticed this issue with one taxon: *Hdis*. I haven't, however, systematically checked other taxa. 

According to ```Sample size``` there are 54 grains of *Hdis*. But under ```Classify``` if you select *Hdis* and any other taxa I get ```infinite or missing values in 'x'```<sup>1</sup>, and if you select it and two other taxa classification works but *Hdis* is absent from ```Per class```.

Note that of only one (not *Hdis*) is selected there is the same error, but if only *Hdis* is selected the error is different: ```non-conformable arrays```<sup>2</sup>.

<sup>1</sup> ```Error in svd(X, nu = 0L) : infinite or missing values in 'x'```
<sup>2</sup> ```Error in x - group.means[g, ] : non-conformable arrays```

**Comment by vbonhomme** [comment]
that's the kind of messages we have when lda is not happy for some reason caused by its calculation. here, I'd say it may be caused by the wrapping paper around because: i) classification seems ok in the app, ii) (more importantly) the message are absent when I do the very same operation outside Shiny.
