### ISSUE TITLE
Clustering - explain it to me

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#38]
As you may now have guessed, I'm having fun playing with ```Clustering```.
Just wondering if you could explain, or more likely point me in the direction of accessible literature (how about _Cluster analysis for Luddite archaeologists_?), that explains the differences between layout (presume largely presentational) and dist and hclust methods?   
Or, at least a rule-of-thumb for which options we should most often focus on.

**Comment by vbonhomme** [comment]
* a nice primer can be found there : https://en.wikipedia.org/wiki/Hierarchical_clustering
* for the dist method euclidean is fine (at least meaningful for human brain); mahanalobis could be use to take into account the 'shape' of ellipses ie the covariance btw groups
* the likage metric for hclust is more touchy. it depends of how we want to gather units and groups from the dist matrix. See https://www.youtube.com/watch?v=VMyXc3SiEqs and possibly other items within the course
* the layout is mainly cosmetics (ie the way/orientation) to display lengths between clades. more importantly, all rooted trees are not really legit in morphometrics as we cant really provide a rooting shape. unfortunately they are the easiest to read. but we have to keep in mind to analyse the topology itself rather than the root->tips layouts.
* overall some people make their wole thesis/career on clustering (hierarchical or not) some that's a pretty large topic.
