### ISSUE TITLE
Flipping of outlines?

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#46]
Can you tell/remind us why the outlines are flipped when they are displayed in the morphospace of GrMoEx? For example, the lateral views are always photographed so that the embryo is to the right of the image; yet in the morphospace the embryo [seems] to always be on the left.

I assume that such flipping has no bearing on the shape analysis, and subsequent PCA. But the flipping can make it more difficult to related the [flipped] silhouette in GrMoEx to the [unflipped] microscopy photograph of the grain.

**Comment by vbonhomme** [comment]
1) because shapes are described from their first point and reconstructed
starting with an angle of 0 radians, which is on the right.
2) you're right only cosmetics consequences, but I will restore a
shp_rotate argument at some point in plot.PCA

2015-10-20 17:31 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Can you tell/remind us why the outlines are flipped when they are
> displayed in the morphospace of GrMoEx? For example, the lateral views are
> always photographed so that the embryo is to the right of the image; yet in
> the morphospace the embryo [seems] to always be on the left.
>
> I assume that such flipping has no bearing on the shape analysis, and
> subsequent PCA. But the flipping can make it more difficult to related the
> [flipped] silhouette in GrMoEx to the [unflipped] microscopy photograph of
> the grain.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/46>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
done
